In [12]:
import numpy as np

#Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
natural_array = np.arange(1, 11, 1)
print(natural_array)

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
#Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
zero_array = np.zeros((3, 3), dtype=int)
print(zero_array)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [21]:
# Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
random_array = np.random.randint(1, 11, (5, 5))
print(random_array)

[[ 7  1 10  4  4]
 [10  4  6  6  9]
 [ 9 10  8  4 10]
 [ 2  2  2  7  7]
 [ 4  5  2 10 10]]


In [22]:
#Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
random_d_array = np.random.random((4, 4))
print(random_d_array)

[[0.30691275 0.50504723 0.16593803 0.68081544]
 [0.79469503 0.61407359 0.85603731 0.70170908]
 [0.80495918 0.5379668  0.95646405 0.63000013]
 [0.29584143 0.97249911 0.83162655 0.77153841]]


In [26]:
#Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
arr_1 = np.random.randint(1, 11, 5)
arr_2 = np.random.randint(1, 11, 5)
suma = arr_1 + arr_2
diff = arr_1 - arr_2
mult = arr_1 * arr_2
div = arr_1 / arr_2
print('Array 1: ', arr_1)
print('Array 2: ', arr_2)
print('Sum: ', suma)
print('Difference: ', diff)
print('Multiple: ', mult)
print('Divide', div)

1:  [ 6  3  5 10  6]
2:  [ 6  8  4 10  8]
Sum:  [12 11  9 20 14]
Difference:  [ 0 -5  1  0 -2]
Multiple:  [ 36  24  20 100  48]
Divide [1.    0.375 1.25  1.    0.75 ]


In [29]:
#Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
v_1 = np.random.randint(1, 11, 7)
v_2 = np.random.randint(1, 11, 7)
scalar = np.dot(v_1, v_2)

print('Vector 1: ', v_1)
print('Vector 2: ', v_2)
print('Scalar product: ', scalar)

Vector 1:  [ 5 10  6  2  7  3  3]
Vector 2:  [2 3 6 2 2 8 2]
Scalar product:  124


In [35]:
#Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
arr_1 = np.random.randint(1, 11, (2, 2))
arr_2 = np.random.randint(1, 11, (2, 3))
mult = np.dot(arr_1, arr_2)
print('Array 1: ')
print( arr_1)
print('Array 2: ')
print(arr_2)
print('Result: ')
print(mult)

Array 1: 
[[4 1]
 [9 6]]
Array 2: 
[[2 3 9]
 [6 4 6]]
Result: 
[[ 14  16  42]
 [ 54  51 117]]


In [43]:
#Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
arr = np.random.randint(1, 11, (3, 3))
arr_rev = np.linalg.inv(arr)
print('Array: ')
print(arr)
print('Invert array: ')
print(arr_rev)

Array: 
[[6 2 5]
 [7 5 8]
 [5 8 6]]
Invert array: 
[[ 0.64150943 -0.52830189  0.16981132]
 [ 0.03773585 -0.20754717  0.24528302]
 [-0.58490566  0.71698113 -0.30188679]]


In [45]:
#Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
arr = np.random.random((4, 4))
arr_transposed = arr.T
print('Array:')
print(arr)
print('Transposed array:')
print(arr_transposed)

Array:
[[0.43803504 0.59194215 0.03945434 0.00099161]
 [0.42579685 0.59491035 0.63687983 0.19730681]
 [0.76652096 0.83331097 0.00336556 0.78582822]
 [0.41784511 0.20327675 0.58962803 0.75822157]]
Transposed array:
[[0.43803504 0.42579685 0.76652096 0.41784511]
 [0.59194215 0.59491035 0.83331097 0.20327675]
 [0.03945434 0.63687983 0.00336556 0.58962803]
 [0.00099161 0.19730681 0.78582822 0.75822157]]


In [49]:
#Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
arr = np.random.randint(1, 11, (3, 4))
vect = np.random.randint(1, 11, 4)
mult = np.dot(arr, vect)
print('Array:')
print(arr)
print('Vector:')
print(vect)
print('Multiple: ')
print(mult)

Array:
[[ 4  7  8  7]
 [ 2 10  1  5]
 [ 6  8  2  7]]
Vector:
[3 6 3 4]
Multiple: 
[106  89 100]


In [53]:
#Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
arr = np.random.random((2, 3))
vect = np.random.random(3)
mult = np.dot(arr, vect)
print('Array:')
print(arr)
print('Vector:')
print(vect)
print('Multiple: ')
print(mult)

Array:
[[0.47563681 0.37189411 0.76631741]
 [0.53775484 0.89956796 0.76160947]]
Vector:
[0.33261139 0.85320544 0.81510601]
Multiple: 
[1.10013422 1.56717212]


In [54]:
#Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
arr_1 = np.random.randint(1, 11, (2, 2))
arr_2 = np.random.randint(1, 11, (2, 2))
mult = arr_1 * arr_2
print('Array 1: ')
print( arr_1)
print('Array 2: ')
print(arr_2)
print('Result: ')
print(mult)

Array 1: 
[[8 5]
 [8 7]]
Array 2: 
[[4 8]
 [7 3]]
Result: 
[[32 40]
 [56 21]]


In [55]:
#Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
arr_1 = np.random.randint(1, 11, (2, 2))
arr_2 = np.random.randint(1, 11, (2, 2))
mult = np.dot(arr_1, arr_2)
print('Array 1: ')
print( arr_1)
print('Array 2: ')
print(arr_2)
print('Result: ')
print(mult)

Array 1: 
[[ 2  3]
 [10  4]]
Array 2: 
[[ 4 10]
 [ 3  1]]
Result: 
[[ 17  23]
 [ 52 104]]


In [57]:
#Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
arr = np.random.randint(1, 101, (5, 5))
suma = arr.sum()
print('Array:')
print(arr)
print('Sum: ', suma)

Array:
[[33 47 25  8 76]
 [12 80 21 33 19]
 [62 46 31 54 73]
 [45 63 10 38 13]
 [77 43 35 45 79]]
Sum:  1068


In [58]:
#Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
arr_1 = np.random.randint(1, 11, (4, 4))
arr_2 = np.random.randint(1, 11, (4, 4))
diff = arr_1 - arr_2
print('Array 1: ')
print( arr_1)
print('Array 2: ')
print(arr_2)
print('Difference: ')
print(diff)

Array 1: 
[[ 4  1  8  5]
 [ 9  3 10  9]
 [ 1  9 10  8]
 [ 7  6  3  5]]
Array 2: 
[[ 1 10  4  9]
 [ 7  9  7  4]
 [ 8 10  2 10]
 [ 8  4 10  4]]
Difference: 
[[ 3 -9  4 -4]
 [ 2 -6  3  5]
 [-7 -1  8 -2]
 [-1  2 -7  1]]


In [61]:
#Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
arr = np.random.random((3, 3))
vect = np.sum(arr, axis = 1, keepdims = True)
print('Array:')
print(arr)
print('Vector:')
print(vect)

Array:
[[0.58457005 0.2427178  0.4607334 ]
 [0.66701273 0.47458854 0.82239369]
 [0.57710612 0.2150357  0.96456282]]
Vector:
[[1.28802125]
 [1.96399496]
 [1.75670464]]


In [64]:
#Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
arr = np.random.randint(1, 11, (3, 4))
square = np.square(arr)
print('Array:')
print(arr)
print('Result: ')
print(square)

Array:
[[ 1  9  7  6]
 [ 5  4  6  4]
 [ 1  8 10  8]]
Result: 
[[  1  81  49  36]
 [ 25  16  36  16]
 [  1  64 100  64]]


In [67]:
#Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел
vect = np.random.randint(1, 51, 4)
sqrt = np.sqrt(vect)
print('Vector: ', vect)
print('Result: ', sqrt )

Vector:  [ 6 17  7 10]
Result:  [2.44948974 4.12310563 2.64575131 3.16227766]
